version: '3.5'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  restapi:
  
    image: ghcr.io/arquisoft/dede_es3b/restapi:bf6ad100ee7c82a45155279e0d86791a55f465ff
    ports:
      - "5000:5000"
  webapp:
  
    image: ghcr.io/arquisoft/dede_es3b/webapp:143a2cacba5744b8970847ee29fc246b6edc7a30
    ports:
      - "3000:3000"
    depends_on: 
      - restapi
  prometheus:
    image: prom/prometheus
    volumes:
      - ./restapi/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - restapi
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./restapi/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - restapi
  gatling:
    image: denvazh/gatling:3.2.1
    volumes:
      - ./webapp/loadtesting/conf
      - ./webapp/loadtesting/results
      - ./webapp/loadtesting/tests